   services:
     app:
       image: devilbox/php-fpm:8.2-work
       container_name: laravel_app
       restart: always
       volumes:
         - ../laravel:/var/www/html
         - ../supervisor/:/etc/supervisor/custom.d/
       working_dir: /var/www/html
       networks:
         - laravel_network
       depends_on:
         - postgres
         - redis

     webserver:
       image: nginx:alpine
       container_name: laravel_webserver
       restart: always
       volumes:
         - ../laravel:/var/www/html
         - ../nginx/nginx.conf:/etc/nginx/conf.d/default.conf
       ports:
         - "80:80"
       networks:
         - laravel_network

     postgres:
       image: postgres:latest
       container_name: laravel_postgres
       restart: always
       environment:
         POSTGRES_USER: user2
         POSTGRES_PASSWORD: password2
         POSTGRES_DB: laravel_testJob
       ports:
         - "5444:5432"
       volumes:
         - pgdata_testJob:/var/lib/postgresql/data
       networks:
         - laravel_network

     redis:
       image: redis:alpine
       container_name: laravel_redis
       restart: always
       networks:
         - laravel_network

   networks:
     laravel_network:
       driver: bridge

   volumes:
     pgdata_testJob: